import type { Metadata } from "next";
import "../styles/globals.css";
import { Footer, NavBar } from "@/components/global";
import { aoboshi_one, poppins, press_start_2p, prosto_one, wallpoet } from "@/constants/fonts";

export const metadata: Metadata = {
  title: "GAMEQUEST | APP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`w-[100%] ${wallpoet.variable} ${prosto_one.variable} ${aoboshi_one.variable} ${poppins.variable} ${press_start_2p.variable}`}>
        <NavBar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
