import type { Metadata } from "next";
import { Wallpoet, Prosto_One, Aoboshi_One, Poppins, Press_Start_2P } from "next/font/google";
import "../styles/globals.css";

const wallpoet = Wallpoet({
  weight: ['400'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--wallpoet'
});
const prosto_one = Prosto_One({
  weight: ['400'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--prosto_one'
});
const aoboshi_one = Aoboshi_One({
  weight: ['400'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--aoboshi_one'
});
const press_start_2p = Press_Start_2P({
  weight: ['400'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--press_start_2p'
});
const poppins = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--poppins'
});

export const metadata: Metadata = {
  title: "GQ App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${wallpoet.variable} ${prosto_one.variable} ${aoboshi_one.variable} ${poppins.variable} ${press_start_2p.variable}`}>{children}</body>
    </html>
  );
}
